# docker network create --driver bridge rag_network || true

services:
  postgresdb:
    image: ankane/pgvector:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d cloud_whisper" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag_network
    profiles: ["basic-setup"]

  web:
    container_name: web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    networks:
      - rag_network
    profiles: ["basic-setup"]

    
volumes:
  pgdata:
    driver: local

networks:
  ai_network:
    external: true